//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TableHeader {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TableHeader() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WIM_MVC.Resource.TableHeader", typeof(TableHeader).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ.
        /// </summary>
        public static string General_DateTime {
            get {
                return ResourceManager.GetString("General_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tải trọng (Kg).
        /// </summary>
        public static string General_GrossWeight {
            get {
                return ResourceManager.GetString("General_GrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng TT cho phép (Kg).
        /// </summary>
        public static string General_GrossWeightAllowable {
            get {
                return ResourceManager.GetString("General_GrossWeightAllowable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn.
        /// </summary>
        public static string General_Lane {
            get {
                return ResourceManager.GetString("General_Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cân đối trái phải (%).
        /// </summary>
        public static string General_LeftRightBalance {
            get {
                return ResourceManager.GetString("General_LeftRightBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài (m).
        /// </summary>
        public static string General_Length {
            get {
                return ResourceManager.GetString("General_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trục.
        /// </summary>
        public static string General_NumberAxis {
            get {
                return ResourceManager.GetString("General_NumberAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Quá tải.
        /// </summary>
        public static string General_PercentOverload {
            get {
                return ResourceManager.GetString("General_PercentOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biển số.
        /// </summary>
        public static string General_PlateNumber {
            get {
                return ResourceManager.GetString("General_PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vận tốc (Km/h).
        /// </summary>
        public static string General_Speed {
            get {
                return ResourceManager.GetString("General_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string General_VehicleType {
            get {
                return ResourceManager.GetString("General_VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lamp {
            get {
                object obj = ResourceManager.GetObject("lamp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức quá tải.
        /// </summary>
        public static string OverLoadLevel {
            get {
                return ResourceManager.GetString("OverLoadLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string User_ConfirmPassword {
            get {
                return ResourceManager.GetString("User_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string User_FirstName {
            get {
                return ResourceManager.GetString("User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        public static string User_LastName {
            get {
                return ResourceManager.GetString("User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng  nhập.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
    }
}
