//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIM_MVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_Dataloger
    {
        public int ID { get; set; }
        public string IP { get; set; }
        public Nullable<int> PORT { get; set; }
        public Nullable<int> TIME_DELTA { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> REBOOT_TIME { get; set; }
        public Nullable<int> TIME_WAIT { get; set; }
    }
}
