//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIM_MVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_Lane
    {
        public int LaneId { get; set; }
        public string LaneCode { get; set; }
        public string StationCode { get; set; }
        public string Name { get; set; }
        public string Direction { get; set; }
        public string LaneType { get; set; }
        public string IpAddress { get; set; }
        public bool IsUsed { get; set; }
        public string Note { get; set; }
    }
}
