//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIM_MVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_VMS
    {
        public int ID { get; set; }
        public string IP { get; set; }
        public Nullable<int> PORT { get; set; }
        public Nullable<int> HEIGHT { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public Nullable<int> CHIP_TYPE { get; set; }
        public string FONT { get; set; }
        public Nullable<double> FONT_SIZE { get; set; }
        public Nullable<int> DISTANCE { get; set; }
        public Nullable<int> WIDTH_INDEX { get; set; }
        public string HEADR { get; set; }
        public Nullable<int> HEIGHT_INDEX { get; set; }
        public Nullable<int> DISPLAY_TIME { get; set; }
        public Nullable<int> DISPLAY_LINE { get; set; }
        public Nullable<byte> DISPLAY_MODE { get; set; }
    }
}
