//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIM_MVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_DeviceStatusLog
    {
        public long ID { get; set; }
        public string ProductID { get; set; }
        public int Type { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> StationID { get; set; }
        public int BeginStatus { get; set; }
        public int EndStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Reason { get; set; }
        public string Note { get; set; }
    }
}
