//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIM_MVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ConfigInfo
    {
        public int ConfigInfoID { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string InfoType { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    }
}
