//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIM_MVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Trans_RawAxles
    {
        public System.Guid AxleId { get; set; }
        public Nullable<System.Guid> TranId { get; set; }
        public Nullable<int> VehicleIdFromLogger { get; set; }
        public Nullable<int> AxleGroupId { get; set; }
        public Nullable<double> Velocity { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<double> GrossWeight { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<double> LeftWeight { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<double> RightWeight { get; set; }
        public Nullable<double> LeftRightImbalance { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<int> OverloadStatus { get; set; }
        public Nullable<double> OverloadPercent { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<double> LimitWeight { get; set; }
    
        public virtual Trans_VehicleInfo Trans_VehicleInfo { get; set; }
    }
}
