//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIM_MVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Trans_VehicleInfo
    {
        public Trans_VehicleInfo()
        {
            this.Trans_RawAxles = new HashSet<Trans_RawAxles>();
        }
    
        public System.Guid TranId { get; set; }
        public Nullable<System.DateTime> WeightBeginTime { get; set; }
        public Nullable<System.DateTime> WeightEndTime { get; set; }
        public Nullable<double> WeightDuration { get; set; }
        public Nullable<int> VehicleIdFromLogger { get; set; }
        public string WeightIdFromLogger { get; set; }
        public Nullable<int> LoggerId { get; set; }
        public Nullable<double> Velocity { get; set; }
        public Nullable<double> VehicleLength { get; set; }
        public Nullable<double> WheelBaseLength { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<double> LeftWeight { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<double> RightWeight { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<double> GrossWeight { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<double> LimitWeight { get; set; }
        public Nullable<double> OverloadPercent { get; set; }
        public Nullable<int> OverloadStatus { get; set; }
        public Nullable<int> TranStatus { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<int> AxlesCount { get; set; }
        public string LaneCode { get; set; }
        public string VehicleTypeCode { get; set; }
        public string TransactionId { get; set; }
    
        public virtual ICollection<Trans_RawAxles> Trans_RawAxles { get; set; }
    }
}
