//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIM_MVC.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WIMEntities : DbContext
    {
        //public WIMEntities()
        //    : base("name=WIMEntities")
        //{
        //}
        public WIMEntities()
            : base(BaseModel.EFConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<LS_AxleType> LS_AxleType { get; set; }
        public virtual DbSet<LS_CameraConfig> LS_CameraConfig { get; set; }
        public virtual DbSet<LS_Dataloger> LS_Dataloger { get; set; }
        public virtual DbSet<LS_Lane> LS_Lane { get; set; }
        public virtual DbSet<LS_Report> LS_Report { get; set; }
        public virtual DbSet<LS_Station> LS_Station { get; set; }
        public virtual DbSet<LS_VehicleType> LS_VehicleType { get; set; }
        public virtual DbSet<LS_VMS> LS_VMS { get; set; }
        public virtual DbSet<SUP_DeviceStatus> SUP_DeviceStatus { get; set; }
        public virtual DbSet<SUP_DeviceStatusHistory> SUP_DeviceStatusHistory { get; set; }
        public virtual DbSet<SUP_DeviceStatusLog> SUP_DeviceStatusLog { get; set; }
        public virtual DbSet<SYS_ConfigInfo> SYS_ConfigInfo { get; set; }
        public virtual DbSet<Trans_VehicleInfo> Trans_VehicleInfo { get; set; }
        public virtual DbSet<Trans_RawAxles> Trans_RawAxles { get; set; }
    }
}
